; This file is for the FamiTone2 library and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_playershoot

@sfx_ntsc_playershoot:
	.byte $84,$ab,$85,$01,$83,$b9,$89,$f0,$01,$84,$59,$83,$bf,$01,$84,$32
	.byte $83,$ba,$01,$84,$3f,$83,$b4,$01,$00

.export sounds
