;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2

@sfx_ntsc_0:
	.byte $84,$ab,$85,$01,$83,$b9,$89,$f0,$01,$84,$59,$83,$bf,$01,$84,$32
	.byte $83,$ba,$01,$84,$3f,$83,$b4,$01,$00
@sfx_pal_0:
	.byte $80,$bf,$81,$8c,$82,$01,$02,$81,$76,$02,$81,$4d,$01,$81,$18,$05
	.byte $00
@sfx_ntsc_1:
	.byte $80,$bf,$81,$54,$82,$00,$04,$81,$6a,$04,$81,$42,$04,$00
@sfx_pal_1:
	.byte $80,$bf,$81,$4e,$82,$00,$04,$81,$62,$04,$81,$3e,$02,$00
@sfx_ntsc_2:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$0a,$00
@sfx_pal_2:
	.byte $89,$3f,$8a,$0d,$01,$89,$3e,$01,$89,$3a,$08,$00